### ISSUE TITLE
#解决zsh补全msfvenom出现_values:compvalues:11: not enough arguments(参数不足)的问题

### ISSUE THREAD

**Issue by fengziHK** [Green-m/msfvenom-zsh-completion#1]
@#2020309

#1、venom-cache(msfvenom --list payloads to list)文件放入~.zsh\

#2、~/.zshrc配置文件

#插件加入

#plugins=(git msfvenom)

#最后加入

#fpath=(~/.zsh/completion $fpath)

#autoload -Uz compinit && compinit -i

**Comment by Green-m** [comment]
这个应该是 payloads 没有缓存，默认应该会自动缓存的，也可以调用函数`venom-cache-payloads` 来手动缓存。

![image](https://user-images.githubusercontent.com/22535454/77873817-a3095e00-727d-11ea-8452-b226da944565.png)

感谢提出问题 @fengziHK
